package specie

import "image/color"

var (
	SpecieAntiLife                      = SpecieConfig{"AntiLife", "B0123478/S01234678", color.White}
	SpecieInverseLife                   = SpecieConfig{"InverseLife", "B0123478/S34678", color.White}
	SpecieB01245_S01245                 = SpecieConfig{"B01245/S01245", "B01245/S01245", color.White}
	SpecieWickstretcherAndTheParasites  = SpecieConfig{"Wickstretcher And The Parasites", "B01356/S012345", color.White}
	SpecieOils                          = SpecieConfig{"Oils", "B014/S2", color.White}
	SpecieB017_S01                      = SpecieConfig{"B017/S01", "B017/S01", color.White}
	SpecieB026_S1                       = SpecieConfig{"B026/S1", "B026/S1", color.White}
	SpecieInvertamaze                   = SpecieConfig{"Invertamaze", "B028/S0124", color.White}
	SpecieNeonBlobs                     = SpecieConfig{"Neon Blobs", "B08/S4", color.White}
	SpecieH_trees                       = SpecieConfig{"H-trees", "B1/S012345678", color.White}
	SpecieFuzz                          = SpecieConfig{"Fuzz", "B1/S014567", color.White}
	SpecieGnarl                         = SpecieConfig{"Gnarl", "B1/S1", color.White}
	SpecieSnakeskin                     = SpecieConfig{"Snakeskin", "B1/S134567", color.White}
	SpecieSolidIslandsGrowAmongstStatic = SpecieConfig{"Solid islands grow amongst static", "B12678/S15678", color.White}
	SpecieReplicator                    = SpecieConfig{"Replicator", "B1357/S1357", color.White}
	SpecieFredkin                       = SpecieConfig{"Fredkin", "B1357/S02468", color.White}
	SpecieFeux                          = SpecieConfig{"Feux", "B1358/S0247", color.White}
	SpecieForrestOfLs                   = SpecieConfig{"Forrest of Ls", "B168/S236", color.White}
	SpecieSeeds                         = SpecieConfig{"Seeds", "B2/S", color.White}
	SpecieLiveFreeOrDie                 = SpecieConfig{"Live Free or Die", "B2/S0", color.White}
	SpecieB2_S13                        = SpecieConfig{"B2/S13", "B2/S13", color.White}
	SpecieB2_S2345                      = SpecieConfig{"B2/S2345", "B2/S2345", color.White}
	SpecieB2_S23456                     = SpecieConfig{"B2/S23456", "B2/S23456", color.White}
	SpecieB2_S2345678                   = SpecieConfig{"B2/S2345678", "B2/S2345678", color.White}
	SpecieServiettes                    = SpecieConfig{"Serviettes", "B234/S", color.White}
	SpecieB25_S4                        = SpecieConfig{"B25/S4", "B25/S4", color.White}
	SpecieIceballs                      = SpecieConfig{"Iceballs", "B25678/S5678", color.White}
	SpecieLifeWithoutDeath              = SpecieConfig{"Life without death", "B3/S012345678", color.White}
	SpecieDotLife                       = SpecieConfig{"DotLife", "B3/S023", color.White}
	SpecieStarTrek                      = SpecieConfig{"Star Trek", "B3/S0248", color.White}
	SpecieFlock                         = SpecieConfig{"Flock", "B3/S12", color.White}
	SpecieMazectric                     = SpecieConfig{"Mazectric", "B3/S1234", color.White}
	SpecieMaze                          = SpecieConfig{"Maze", "B3/S12345", color.White}
	SpecieMagnezones                    = SpecieConfig{"Magnezones", "B3/S123678", color.White}
	SpecieSnowLife                      = SpecieConfig{"SnowLife", "B3/S1237", color.White}
	SpecieCorrosionOfConformity         = SpecieConfig{"Corrosion of Conformity", "B3/S124", color.White}
	SpecieEightFlock                    = SpecieConfig{"EightFlock", "B3/S128", color.White}
	SpecieLowLife                       = SpecieConfig{"LowLife", "B3/S13", color.White}
	SpecieB3_S2                         = SpecieConfig{"B3/S2", "B3/S2", color.White}
	SpecieConwaysLife                   = SpecieConfig{"Conway's Life", "B3/S23", color.White}
	SpecieB3_S2378                      = SpecieConfig{"B3/S2378", "B3/S2378", color.White}
	SpecieEightLife                     = SpecieConfig{"EightLife", "B3/S238", color.White}
	SpecieShootsAndRoots                = SpecieConfig{"Shoots and Roots", "B3/S245678", color.White}
	SpecieLifeguard2                    = SpecieConfig{"Lifeguard 2", "B3/S4567", color.White}
	SpecieCoral                         = SpecieConfig{"Coral", "B3/S45678", color.White}
	Specie3_4Life                       = SpecieConfig{"3-4 Life", "B34/S34", color.White}
	SpecieDance                         = SpecieConfig{"Dance", "B34/S35", color.White}
	SpecieBacteria                      = SpecieConfig{"Bacteria", "B34/S456", color.White}
	SpecieNeverHappy                    = SpecieConfig{"Never happy", "B345/S0456", color.White}
	SpecieBlinkers                      = SpecieConfig{"Blinkers", "B345/S2", color.White}
	SpecieAssimilation                  = SpecieConfig{"Assimilation", "B345/S4567", color.White}
	SpecieLongLife                      = SpecieConfig{"Long Life", "B345/S5", color.White}
	SpecieSpiralAndPolygonalGrowth      = SpecieConfig{"Spiral and polygonal growth", "B34568/S15678", color.White}
	SpecieGems                          = SpecieConfig{"Gems", "B3457/S4568", color.White}
	SpecieGemsMinor                     = SpecieConfig{"Gems Minor", "B34578/S456", color.White}
	SpecieGroundedLife                  = SpecieConfig{"Grounded Life", "B35/S23", color.White}
	SpecieLandRush                      = SpecieConfig{"Land Rush", "B35/S234578", color.White}
	SpecieEppstein                      = SpecieConfig{"Eppstein", "B35/S236", color.White}
	SpecieBugs                          = SpecieConfig{"Bugs", "B3567/S15678", color.White}
	SpecieCheerios                      = SpecieConfig{"Cheerios", "B35678/S34567", color.White}
	SpecieHolstein                      = SpecieConfig{"Holstein", "B35678/S4678", color.White}
	SpecieDiamoeba                      = SpecieConfig{"Diamoeba", "B35678/S5678", color.White}
	SpecieAmoeba                        = SpecieConfig{"Amoeba", "B357/S1358", color.White}
	SpeciePseudoLife                    = SpecieConfig{"Pseudo Life", "B357/S238", color.White}
	SpecieGeology                       = SpecieConfig{"Geology", "B3578/S24678", color.White}
	SpecieHighFlock                     = SpecieConfig{"HighFlock", "B36/S12", color.White}
	Specie2x2                           = SpecieConfig{"2×2", "B36/S125", color.White}
	SpecieIronFlock                     = SpecieConfig{"IronFlock", "B36/S128", color.White}
	SpecieHighLife                      = SpecieConfig{"HighLife", "B36/S23", color.White}
	SpecieLandRush2                     = SpecieConfig{"Land Rush 2", "B36/S234578", color.White}
	SpecieVirus                         = SpecieConfig{"Virus", "B36/S235", color.White}
	SpecieIronLife                      = SpecieConfig{"IronLife", "B36/S238", color.White}
	SpecieSqrtReplicatorRule            = SpecieConfig{"sqrt replicator rule", "B36/S245", color.White}
	SpecieSlowBlob                      = SpecieConfig{"Slow Blob", "B367/S125678", color.White}
	SpecieDrighLife                     = SpecieConfig{"DrighLife", "B367/S23", color.White}
	Specie2x2_2                         = SpecieConfig{"2×2 2", "B3678/S1258", color.White}
	SpecieCastles                       = SpecieConfig{"Castles", "B3678/S135678", color.White}
	SpecieB3678_S23                     = SpecieConfig{"B3678/S23", "B3678/S23", color.White}
	SpecieStains                        = SpecieConfig{"Stains", "B3678/S235678", color.White}
	SpecieDayAndNight                   = SpecieConfig{"Day & Night", "B3678/S34678", color.White}
	SpecieLowDeathWithoutDeath          = SpecieConfig{"LowDeath without Death", "B368/S012345678", color.White}
	SpecieB368_S12578                   = SpecieConfig{"B368/S12578", "B368/S12578", color.White}
	SpecieLowFlockDeath                 = SpecieConfig{"LowFlockDeath", "B368/S128", color.White}
	SpecieLifeSkyHigh                   = SpecieConfig{"Life SkyHigh", "B368/S236", color.White}
	SpecieLowDeath                      = SpecieConfig{"LowDeath", "B368/S238", color.White}
	SpecieMorley                        = SpecieConfig{"Morley", "B368/S245", color.White}
	SpecieDryLifeWithoutDeath           = SpecieConfig{"DryLife without Death", "B37/S012345678", color.White}
	SpecieDryFlock                      = SpecieConfig{"DryFlock", "B37/S12", color.White}
	SpecieMazectricWithMice             = SpecieConfig{"Mazectric with Mice", "B37/S1234", color.White}
	SpecieMazeWithMice                  = SpecieConfig{"Maze with Mice", "B37/S12345", color.White}
	SpecieDryLife                       = SpecieConfig{"DryLife", "B37/S23", color.White}
	SpeciePlowWorld                     = SpecieConfig{"Plow World", "B378/S012345678", color.White}
	SpecieCoagulations                  = SpecieConfig{"Coagulations", "B378/S235678", color.White}
	SpeciePedestrianLifeWithoutDeath    = SpecieConfig{"Pedestrian Life without Death", "B38/S012345678", color.White}
	SpeciePedestrianFlock               = SpecieConfig{"Pedestrian Flock", "B38/S12", color.White}
	SpecieHoneyFlock                    = SpecieConfig{"HoneyFlock", "B38/S128", color.White}
	SpeciePedestrianLife                = SpecieConfig{"Pedestrian Life", "B38/S23", color.White}
	SpecieHoneyLife                     = SpecieConfig{"HoneyLife", "B38/S238", color.White}
	SpecieElectrifiedMaze               = SpecieConfig{"Electrified Maze", "B45/S12345", color.White}
	SpecieOscillatorsRule               = SpecieConfig{"Oscillators Rule", "B45/S1235", color.White}
	SpecieWalledCities                  = SpecieConfig{"Walled cities", "B45678/S2345", color.White}
	SpecieMajority                      = SpecieConfig{"Majority", "B45678/S5678", color.White}
	SpecieVote4_5                       = SpecieConfig{"Vote 4/5", "B4678/S35678", color.White}
	SpecieLifeguard1                    = SpecieConfig{"Lifeguard 1", "B48/S234", color.White}
	SpecieRingsNSlugs                   = SpecieConfig{"Rings 'n' Slugs", "B56/S14568", color.White}
	SpecieVote                          = SpecieConfig{"Vote", "B5678/S45678", color.White}
)
