package specie

var (
	SpecieAntiLife                      = SpecieConfig{"AntiLife", "B0123478/S01234678"}
	SpecieInverseLife                   = SpecieConfig{"InverseLife", "B0123478/S34678"}
	SpecieB01245_S01245                 = SpecieConfig{"B01245/S01245", "B01245/S01245"}
	SpecieWickstretcherAndTheParasites  = SpecieConfig{"Wickstretcher And The Parasites", "B01356/S012345"}
	SpecieOils                          = SpecieConfig{"Oils", "B014/S2"}
	SpecieB017_S01                      = SpecieConfig{"B017/S01", "B017/S01"}
	SpecieB026_S1                       = SpecieConfig{"B026/S1", "B026/S1"}
	SpecieInvertamaze                   = SpecieConfig{"Invertamaze", "B028/S0124"}
	SpecieNeonBlobs                     = SpecieConfig{"Neon Blobs", "B08/S4"}
	SpecieH_trees                       = SpecieConfig{"H-trees", "B1/S012345678"}
	SpecieFuzz                          = SpecieConfig{"Fuzz", "B1/S014567"}
	SpecieGnarl                         = SpecieConfig{"Gnarl", "B1/S1"}
	SpecieSnakeskin                     = SpecieConfig{"Snakeskin", "B1/S134567"}
	SpecieSolidIslandsGrowAmongstStatic = SpecieConfig{"Solid islands grow amongst static", "B12678/S15678"}
	SpecieReplicator                    = SpecieConfig{"Replicator", "B1357/S1357"}
	SpecieFredkin                       = SpecieConfig{"Fredkin", "B1357/S02468"}
	SpecieFeux                          = SpecieConfig{"Feux", "B1358/S0247"}
	SpecieForrestOfLs                   = SpecieConfig{"Forrest of Ls", "B168/S236"}
	SpecieSeeds                         = SpecieConfig{"Seeds", "B2/S"}
	SpecieLiveFreeOrDie                 = SpecieConfig{"Live Free or Die", "B2/S0"}
	SpecieB2_S13                        = SpecieConfig{"B2/S13", "B2/S13"}
	SpecieB2_S2345                      = SpecieConfig{"B2/S2345", "B2/S2345"}
	SpecieB2_S23456                     = SpecieConfig{"B2/S23456", "B2/S23456"}
	SpecieB2_S2345678                   = SpecieConfig{"B2/S2345678", "B2/S2345678"}
	SpecieServiettes                    = SpecieConfig{"Serviettes", "B234/S"}
	SpecieB25_S4                        = SpecieConfig{"B25/S4", "B25/S4"}
	SpecieIceballs                      = SpecieConfig{"Iceballs", "B25678/S5678"}
	SpecieLifeWithoutDeath              = SpecieConfig{"Life without death", "B3/S012345678"}
	SpecieDotLife                       = SpecieConfig{"DotLife", "B3/S023"}
	SpecieStarTrek                      = SpecieConfig{"Star Trek", "B3/S0248"}
	SpecieFlock                         = SpecieConfig{"Flock", "B3/S12"}
	SpecieMazectric                     = SpecieConfig{"Mazectric", "B3/S1234"}
	SpecieMaze                          = SpecieConfig{"Maze", "B3/S12345"}
	SpecieMagnezones                    = SpecieConfig{"Magnezones", "B3/S123678"}
	SpecieSnowLife                      = SpecieConfig{"SnowLife", "B3/S1237"}
	SpecieCorrosionOfConformity         = SpecieConfig{"Corrosion of Conformity", "B3/S124"}
	SpecieEightFlock                    = SpecieConfig{"EightFlock", "B3/S128"}
	SpecieLowLife                       = SpecieConfig{"LowLife", "B3/S13"}
	SpecieB3_S2                         = SpecieConfig{"B3/S2", "B3/S2"}
	SpecieConwaysLife                   = SpecieConfig{"Conway's Life", "B3/S23"}
	SpecieB3_S2378                      = SpecieConfig{"B3/S2378", "B3/S2378"}
	SpecieEightLife                     = SpecieConfig{"EightLife", "B3/S238"}
	SpecieShootsAndRoots                = SpecieConfig{"Shoots and Roots", "B3/S245678"}
	SpecieLifeguard2                    = SpecieConfig{"Lifeguard 2", "B3/S4567"}
	SpecieCoral                         = SpecieConfig{"Coral", "B3/S45678"}
	Specie3_4Life                       = SpecieConfig{"3-4 Life", "B34/S34"}
	SpecieDance                         = SpecieConfig{"Dance", "B34/S35"}
	SpecieBacteria                      = SpecieConfig{"Bacteria", "B34/S456"}
	SpecieNeverHappy                    = SpecieConfig{"Never happy", "B345/S0456"}
	SpecieBlinkers                      = SpecieConfig{"Blinkers", "B345/S2"}
	SpecieAssimilation                  = SpecieConfig{"Assimilation", "B345/S4567"}
	SpecieLongLife                      = SpecieConfig{"Long Life", "B345/S5"}
	SpecieSpiralAndPolygonalGrowth      = SpecieConfig{"Spiral and polygonal growth", "B34568/S15678"}
	SpecieGems                          = SpecieConfig{"Gems", "B3457/S4568"}
	SpecieGemsMinor                     = SpecieConfig{"Gems Minor", "B34578/S456"}
	SpecieGroundedLife                  = SpecieConfig{"Grounded Life", "B35/S23"}
	SpecieLandRush                      = SpecieConfig{"Land Rush", "B35/S234578"}
	SpecieEppstein                      = SpecieConfig{"Eppstein", "B35/S236"}
	SpecieBugs                          = SpecieConfig{"Bugs", "B3567/S15678"}
	SpecieCheerios                      = SpecieConfig{"Cheerios", "B35678/S34567"}
	SpecieHolstein                      = SpecieConfig{"Holstein", "B35678/S4678"}
	SpecieDiamoeba                      = SpecieConfig{"Diamoeba", "B35678/S5678"}
	SpecieAmoeba                        = SpecieConfig{"Amoeba", "B357/S1358"}
	SpeciePseudoLife                    = SpecieConfig{"Pseudo Life", "B357/S238"}
	SpecieGeology                       = SpecieConfig{"Geology", "B3578/S24678"}
	SpecieHighFlock                     = SpecieConfig{"HighFlock", "B36/S12"}
	Specie2x2                           = SpecieConfig{"2×2", "B36/S125"}
	SpecieIronFlock                     = SpecieConfig{"IronFlock", "B36/S128"}
	SpecieHighLife                      = SpecieConfig{"HighLife", "B36/S23"}
	SpecieLandRush2                     = SpecieConfig{"Land Rush 2", "B36/S234578"}
	SpecieVirus                         = SpecieConfig{"Virus", "B36/S235"}
	SpecieIronLife                      = SpecieConfig{"IronLife", "B36/S238"}
	SpecieSqrtReplicatorRule            = SpecieConfig{"sqrt replicator rule", "B36/S245"}
	SpecieSlowBlob                      = SpecieConfig{"Slow Blob", "B367/S125678"}
	SpecieDrighLife                     = SpecieConfig{"DrighLife", "B367/S23"}
	Specie2x2_2                         = SpecieConfig{"2×2 2", "B3678/S1258"}
	SpecieCastles                       = SpecieConfig{"Castles", "B3678/S135678"}
	SpecieB3678_S23                     = SpecieConfig{"B3678/S23", "B3678/S23"}
	SpecieStains                        = SpecieConfig{"Stains", "B3678/S235678"}
	SpecieDayAndNight                   = SpecieConfig{"Day & Night", "B3678/S34678"}
	SpecieLowDeathWithoutDeath          = SpecieConfig{"LowDeath without Death", "B368/S012345678"}
	SpecieB368_S12578                   = SpecieConfig{"B368/S12578", "B368/S12578"}
	SpecieLowFlockDeath                 = SpecieConfig{"LowFlockDeath", "B368/S128"}
	SpecieLifeSkyHigh                   = SpecieConfig{"Life SkyHigh", "B368/S236"}
	SpecieLowDeath                      = SpecieConfig{"LowDeath", "B368/S238"}
	SpecieMorley                        = SpecieConfig{"Morley", "B368/S245"}
	SpecieDryLifeWithoutDeath           = SpecieConfig{"DryLife without Death", "B37/S012345678"}
	SpecieDryFlock                      = SpecieConfig{"DryFlock", "B37/S12"}
	SpecieMazectricWithMice             = SpecieConfig{"Mazectric with Mice", "B37/S1234"}
	SpecieMazeWithMice                  = SpecieConfig{"Maze with Mice", "B37/S12345"}
	SpecieDryLife                       = SpecieConfig{"DryLife", "B37/S23"}
	SpeciePlowWorld                     = SpecieConfig{"Plow World", "B378/S012345678"}
	SpecieCoagulations                  = SpecieConfig{"Coagulations", "B378/S235678"}
	SpeciePedestrianLifeWithoutDeath    = SpecieConfig{"Pedestrian Life without Death", "B38/S012345678"}
	SpeciePedestrianFlock               = SpecieConfig{"Pedestrian Flock", "B38/S12"}
	SpecieHoneyFlock                    = SpecieConfig{"HoneyFlock", "B38/S128"}
	SpeciePedestrianLife                = SpecieConfig{"Pedestrian Life", "B38/S23"}
	SpecieHoneyLife                     = SpecieConfig{"HoneyLife", "B38/S238"}
	SpecieElectrifiedMaze               = SpecieConfig{"Electrified Maze", "B45/S12345"}
	SpecieOscillatorsRule               = SpecieConfig{"Oscillators Rule", "B45/S1235"}
	SpecieWalledCities                  = SpecieConfig{"Walled cities", "B45678/S2345"}
	SpecieMajority                      = SpecieConfig{"Majority", "B45678/S5678"}
	SpecieVote4_5                       = SpecieConfig{"Vote 4/5", "B4678/S35678"}
	SpecieLifeguard1                    = SpecieConfig{"Lifeguard 1", "B48/S234"}
	SpecieRingsNSlugs                   = SpecieConfig{"Rings 'n' Slugs", "B56/S14568"}
	SpecieVote                          = SpecieConfig{"Vote", "B5678/S45678"}
)
